# Generated by Django 3.0.2 on 2021-01-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_lawyer_scn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
