# Generated by Django 3.1.7 on 2021-04-03 15:17

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210125_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilian',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='civilian',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='longitude',
        ),
        migrations.AddField(
            model_name='civilian',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(8.991656829394168, 7.432405867962554), srid=4326),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(8.991656829394168, 7.432405867962554), srid=4326),
        ),
    ]
