# Generated by Django 3.1.7 on 2021-04-04 23:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210403_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
