# Generated by Django 3.1.7 on 2021-04-04 23:37

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210405_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(8.991656829394168, 7.432405867962554), geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name=django.contrib.gis.geos.point.Point(8.991656829394168, 7.432405867962554)),
        ),
    ]
