# Generated by Django 3.1.7 on 2021-04-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210405_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='distance',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
