# Generated by Django 3.1.7 on 2021-04-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_lawyer_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='distance',
        ),
    ]
